### ISSUE TITLE
Doughnut chart's Legend demo doesn't work

### ISSUE THREAD

**Issue by valadzhov** [IgniteUI/igniteui-docfx#1214] opened 2019-04-24 13:54 UTC
1. Open https://www.infragistics.com/products/ignite-ui-angular/angular/components/doughnutchart.html
2. Scroll down to Legend Demo
3. Examine the demo

Actual results:
The demo is not shown.

Expected results:
The demo should be shown.

**Comment by zdrawku** [comment] 2019-05-07 10:56
Error is thrown "ERROR Error: Uncaught (in promise): Error: Cannot match any routes. URL Segment: 'charts/doughnut-chart-legend'
Error: Cannot match any routes. URL Segment: 'charts/doughnut-chart-legend'" 

The URL itself can be wrong.

**Comment by HUSSAR-mtrela** [comment] 2019-07-01 16:02
this issue is a duplicate of issue #1135

**Closed by HUSSAR-mtrela** 2019-07-01 16:02 UTC
Labels: category-bug, category-duplicate
