### ISSUE TITLE
Combo page does not load navigation, right side menu, or top bar

### ISSUE THREAD

**Issue by ig-ealbert** [IgniteUI/igniteui-docfx#492] opened 2018-06-27 19:02 UTC
https://staging.infragistics.local/angularsite/components/combo.html

**Comment by kdinev** [comment] 2018-06-28 06:52
I cannot reproduce it. I guess it was because the sample hadn't been merged yet.

**Closed by kdinev** 2018-06-28 06:52 UTC

**Comment by ig-ealbert** [comment] 2018-06-28 13:53
Yes, it loads now.
