### ISSUE TITLE
Update License FAQ and Installation

### ISSUE THREAD

**Issue by radomirchev** [IgniteUI/igniteui-docfx#3513] opened 2023-02-27 15:31 UTC
Because of breaking change in npm v9

npm adduser --registry=https://packages.infragistics.com/npm/js-licensed/ --scope=@infragistics --always-auth

gives following Error: 

npm ERR! code ENYI
npm ERR! Web login not supported

We need to add: 

 NOTE: if you're using npm 9+ you need to set --auth-type=legacy

**Comment by damyanpetev** [comment] 2023-02-28 12:40
Related to or possibly a duplicate of https://github.com/IgniteUI/igniteui-docfx/issues/3476
IIRC there's also a distinction between what `login` and `adduser` do with npm 9, so we might need to adjust for that as well

**Comment by zdrawku** [comment] 2023-02-28 13:00
For the time being I am merging the change from Rado and closing this work item. We will use the one created by Martin to address `login` and `addUser` specifics

**Closed** 2023-02-28 13:12 UTC
Labels: :new: status: new
